// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDevice(arg1:string):Promise<Array<main.Device>>;

export function DeleteRecent(arg1:number):Promise<void>;

export function FastForward(arg1:string):Promise<void>;

export function GetDevices():Promise<Array<main.Device>>;

export function GetRecent():Promise<Array<main.Recent>>;

export function PlayVLC(arg1:string,arg2:string):Promise<string>;

export function Rewind(arg1:string):Promise<void>;

export function StartStatusMonitor():Promise<void>;

export function TogglePause(arg1:string):Promise<void>;
