// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function DeleteRecent(arg1) {
  return window['go']['main']['App']['DeleteRecent'](arg1);
}

export function EmergencyKill() {
  return window['go']['main']['App']['EmergencyKill']();
}

export function FastForward(arg1) {
  return window['go']['main']['App']['FastForward'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetRecent() {
  return window['go']['main']['App']['GetRecent']();
}

export function PlayVLC(arg1, arg2) {
  return window['go']['main']['App']['PlayVLC'](arg1, arg2);
}

export function Rewind(arg1) {
  return window['go']['main']['App']['Rewind'](arg1);
}

export function StartStatusMonitor() {
  return window['go']['main']['App']['StartStatusMonitor']();
}

export function TogglePause(arg1) {
  return window['go']['main']['App']['TogglePause'](arg1);
}
